"""Add horarios

Revision ID: 0575d617bd36
Revises: 69fda0aa3096
Create Date: 2025-12-02 19:46:43.595824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0575d617bd36'
down_revision: Union[str, Sequence[str], None] = '69fda0aa3096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctores',
    sa.Column('id_doctor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=100), nullable=True),
    sa.Column('especializacion', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_doctor')
    )
    op.create_index(op.f('ix_doctores_id_doctor'), 'doctores', ['id_doctor'], unique=False)
    op.create_table('horarios',
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.String(length=10), nullable=False),
    sa.Column('hora_fin', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_index(op.f('ix_horarios_id_horario'), 'horarios', ['id_horario'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasenia', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('citas',
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('hora_cita', sa.String(length=10), nullable=False),
    sa.Column('dia_cita', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_doctor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctores.id_doctor'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.create_index(op.f('ix_citas_id_cita'), 'citas', ['id_cita'], unique=False)
    op.create_table('horarios_doctores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_doctor', sa.Integer(), nullable=False),
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctores.id_doctor'], ),
    sa.ForeignKeyConstraint(['id_horario'], ['horarios.id_horario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_doctores_id'), 'horarios_doctores', ['id'], unique=False)
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_horarios_doctores_id'), table_name='horarios_doctores')
    op.drop_table('horarios_doctores')
    op.drop_index(op.f('ix_citas_id_cita'), table_name='citas')
    op.drop_table('citas')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_horarios_id_horario'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_doctores_id_doctor'), table_name='doctores')
    op.drop_table('doctores')
    # ### end Alembic commands ###
